export { default as Home } from './Home'
export { default as Profile } from './Profile'
export { default as Favorites } from './Favorites'
export { default as Shopping } from './Shopping'
export { default as Products } from './Products'
export { default as Detail } from './Detail'
export { default as NotFound } from './NotFound'
